# File: azure-pipelines.yml
trigger: none
pr: none
#################################################
# Parameters
#################################################
parameters:
- name: environments
  type: object
  default:
  - appVersionToDeploy: 'deploy-feature-branch-code'
    terraformModuleVersionToUse: 'latest'
    environmentName: dev
    variableGroupName: cfs-data-firstwrap-databricks-ingestion-dev
    platformVariableGroupName: cfs-data-platform-terraform-spn-np
    adbSPNVariableGroupName: cfs-data-firstwrap-databricks-infra-dev
    service_connection_name: sc-subsc-np-fwd-001
    bicep_pool_name: Windows-NP
    terraform_pool_name: Windows-NP
    requiredTerraformVersion: 1.3.6
    # No approvals required - for automated PR validation.
  - appVersionToDeploy: 'latest'

    terraformModuleVersionToUse: 'latest'
    environmentName: as_dev
    variableGroupName: cfs-data-firstwrap-databricks-ingestion-tst1
    platformVariableGroupName: cfs-data-platform-terraform-spn-np
    adbSPNVariableGroupName: cfs-data-firstwrap-databricks-infra-tst1
    service_connection_name: HubServiceConnection
    bicep_pool_name: AS-Windows
    terraform_pool_name: AS-Windows
    requiredTerraformVersion: 1.3.6
    # Approval is set at environment level - SPN is shared in NP so cant be set at variable group without breaking automated PR check.
#################################################
# Job Definition
#################################################
extends:
  template: terraform-plan-apply.yml
  parameters:
    environments: ${{ parameters.environments }}
